catalog: sh -c "cd ./apps/catalog && bundle exec rerun main.rb"
crawler: sh -c "cd ./apps/crawler && bundle exec rerun main.rb"
tg_bot: sh -c "cd ./apps/tg_bot && bundle exec rerun main.rb"
web_chat: sh -c "cd ./apps/web_chat && bundle exec rerun main.rb"
web_search: sh -c "cd ./apps/web_search && bundle exec rerun main.rb"
