# frozen_string_literal: true

source "https://rubygems.org"

group :development, :test do
  gem "rerun"
end

gem "rspec", "~> 3.12", :group => :test

gem "nokogiri", "~> 1.14"

gem "vcr", "~> 6.1", :group => :test

gem "sequel", "~> 5.67"

gem 'sqlite3'

gem "webmock", "~> 3.18", :group => :test

gem "dotenv", "~> 2.8"

gem "rollbar", "~> 3.4"
