# frozen_string_literal: true

source 'https://rubygems.org'

gem 'dotenv'

group :development, :test do
  gem "rerun"
  gem "rack-test"
end


gem "rspec", "~> 3.12", :group => :test
gem "sequel", "~> 5.67"
gem 'sqlite3'
gem "bigdecimal", "~> 3.1"
gem "redis", "~> 5.4"
gem "rack"
gem "puma"
