# frozen_string_literal: true

source "https://rubygems.org"

group :development, :test do
  gem "rerun"
end

gem "rspec", "~> 3.12", :group => :test

gem "sequel", "~> 5.67"

gem 'sqlite3'

gem "dotenv", "~> 3.0"

gem "telegram-bot-ruby", "~> 2.0"

gem "time_difference", "~> 0.7.0"

gem "bigdecimal", "~> 3.1"

gem 'rollbar'