# frozen_string_literal: true

source "https://rubygems.org"

group :development, :test do
  gem "rerun"
end

gem "rspec", "~> 3.12", :group => :test

gem "sequel", "~> 5.67"

gem 'sqlite3'

gem "dotenv", "~> 2.8"

gem "telegram-bot-ruby", "~> 1.0"
