# frozen_string_literal: true

source "https://rubygems.org"

gem "rack", "~> 2.2"
gem "puma", "~> 5.0"
gem "sequel", "~> 5.67"
gem "sqlite3"
gem "turbo-rails", "~> 1.0"
gem "dotenv", "~> 3.0"

group :development, :test do
  gem "rerun"
  gem "rspec", "~> 3.12"
end
