name: RSpec Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [catalog, crawler, tg_bot]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          cd apps/${{ matrix.app }}
          bundle install

      - name: Run RSpec tests
        run: |
          cd apps/${{ matrix.app }}
          bundle exec rspec
